export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const SAVE_WEATHER_DATA = 'SAVE_WEATHER_DATA';

export const SAVE_PLACES = 'SAVE_PLACES';
export const GET_PLACES = 'GET_PLACES';
export const SET_PLACE_LOADING = 'SET_PLACE_LOADING';
export const ADD_PLACE = 'ADD_PLACE';
export const FILTER_PLACE = 'FILTER_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';
